[package]
name = "linalg_bench"
version = "0.1.0"
authors = ["Sébastien Crozet <developer@crozet.re>"]

[dependencies]
nalgebra        = { version = "*", path = "../nalgebra-dev", features = [ "debug" ] }
nalgebra-lapack = { version = "*", path = "../nalgebra-dev/nalgebra-lapack" }
rulinalg        = { version = "*", git = "https://github.com/sebcrozet/rulinalg" }
rand            = "*"
cgmath          = { version = "*", features = [ "simd" ] }
ndarray         = "0.9"
linxal          = { version = "*", features = [ "openblas" ] }
ndarray-linalg  = { version = "*", features = [ "openblas" ] }
